---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(CodeClanData)
library(janitor)
library(tidyr)
```
Q1.1
```{r}
Card_info <- read_csv('data/CardBase.csv') 
Customer_info <- read_csv('data/CustomerBase.csv')
Fraud_info <- read_csv('data/FraudBase.csv')
Transaction_info <- read_csv('data/TransactionBase.csv')

```

```{r}
Cards_clean <- Card_info %>% 
  clean_names()

Customers_clean <- Customer_info %>% 
  clean_names()

Frauds_clean <- Fraud_info %>% 
  clean_names()

Transactions_clean <- Transaction_info %>% 
  clean_names()
```
Q1.2
```{r}
#Card_info
#Customer_info
#Joined_card_details %>% 
left_join(Card_info, Customer_info, by = "Cust_ID")
  
```
Q1.3
```{r}
#Transaction_info
#Fraud_info
full_join(Fraud_info, Transaction_info, by = "Transaction_ID")
```

Q1.4
```{r}
semi_join(Card_info, Transaction_info, by = c("Card_Number" = "Credit_Card_ID"))
```
Q2.1
```{r}
Hat_data <- read_csv('data/hat_observations.csv')

Hat_data
```

```{r}
Separated_hat_info <- Hat_data %>% 
  separate(col = observation,
           into = c("hat_colour", "hat_type"),
           sep = "/")

Separated_hat_info
```

```{r}

hat_observations_date <- Separated_hat_info %>% 
  unite("date", day:year, sep = "-") 

hat_observations_date %>% 
  filter(hat_type == "beret") %>% 
  group_by(date) %>% 
  summarise(total = sum(observation_count)) %>% 
  slice_max(total)

```


```{r}
United_date <- Hat_data %>% 
  unite(col = date,
        c("day", "month", "year"),
        sep = ":")

hat_observations_date <- Hat_data %>% 
  filter(hat_type == "beret") %>% 
  group_by(date) %>% 
  summarise(total = sum(observation_count)) %>% 
  slice_max(total)

United_date
hat_observations_date
```



```{r}
United_datasets <- bind_rows(Card_info, Customer_info, Transaction_info, Fraud_info) %>% 
  select(Age, Customer_Segment, Customer_Vintage_Group, Transaction_ID, Credit_Card_ID, Transaction_Value, Transaction_Segment, Fraud_Flag) %>% 
    drop_na()

United_datasets
```

```{r}
Card_info %>% 
  inner_join(Customer_info, by = "Cust_ID") %>% 
  inner_join(Transaction_info, by = c("Card_Number" = "Credit_Card_ID")) %>% 
  inner_join(Fraud_info, by = "Transaction_ID")
```

```{r}
Exam_results <- read_csv('data/exam_scores.csv')

Exam_results
```


```{r}
Exam_results <- read_csv('data/exam_scores.csv')

Exam_results
```

```{r}
New_results <- Exam_results %>% 
  pivot_longer(cols = starts_with("EX"),
               names_to = "Exam_question",
               names_prefix = "EX",
               values_to = "Score")
New_results
```

```{r}

exam_scores_long <- Exam_results %>% 
  pivot_longer(exam_Q1:exam_Q10, names_to = "exam_question", values_to = "score") 

exam_scores_long %>% 
  separate(exam_question, sep = "Q", into = c("extra_column", "exam_question")) %>% 
  select(-extra_column)

```

