---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(CodeClanData)
```

```{r}
Good_reads <- read_csv('data/books.csv')

Good_reads
```

```{r}
Good_reads %>% 
  pull()
```

```{r}
head(Good_reads)

tail(Good_reads)

dim(Good_reads)

glimpse(Good_reads)

names(Good_reads)

head(Good_reads)

sum(is.na(Good_reads))
```

```{r}
book_subset <- Good_reads %>% 
  select(authors, title, ratings_count, text_reviews_count, language_code, publisher, bookID)
```

```{r}
Good_reads %>% 
  select(authors, title, ratings_count, text_reviews_count, language_code, publisher) %>% 
  filter(is.na(authors)) %>% 
  summarise(count_of_missing_authors = n())
```
Q1
```{r}
Highest_average_rating <- Good_reads %>% 
  select(title, average_rating, bookID) %>%
  arrange(desc(average_rating)) %>% 
  head(5) 

Highest_average_rating
```
Q2
```{r}
most_reviews <- Good_reads %>% 
  select(title, text_reviews_count, bookID) %>% 
  arrange(desc(text_reviews_count)) %>% 
  head(1) 
  

most_reviews
```
Q3
```{r}
most_ratings <- Good_reads %>% 
  select(title, ratings_count, bookID) %>% 
  arrange(desc(ratings_count)) %>% 
  head(1)

most_ratings
```

```{r}
least_ratings <- Good_reads %>% 
  select(title, ratings_count, bookID) %>% 
  arrange(ratings_count) %>% 
  head(1)

least_ratings
```
Q4
```{r}
highest_rating_publisher <- Good_reads %>% 
  select(publisher, average_rating) %>% 
  group_by(publisher) %>% 
  summarise(mean_ratings = mean(average_rating)) %>% 
  arrange(desc(mean_ratings)) %>% 
  head(1)


highest_rating_publisher
```

```{r}
#highest_rating_median_publisher <- Good_reads %>% 
  #select(publisher, average_rating) %>% 
  #group_by(publisher) %>% 
  #summarise(median_ratings = median(average_rating)) %>% 
  #arrange(desc(median_ratings)) %>% 
  #head(1)


#highest_rating_median_publisher
```

```{r}
Highest_page_count <- Good_reads %>% 
  select(language_code, num_pages) %>% 
  summarise(num_pages, language_code) %>% 
  arrange(desc(num_pages))


Highest_page_count
```

```{r}
Highest_language_code <- Good_reads %>% 
  select(language_code, average_rating) %>% 
  summarise(max(average_rating)) 

Highest_language_code  
```
Q5
```{r}
Longest_language_Code <- Good_reads %>% 
  select(language_code, num_pages) %>% 
  group_by(language_code) %>% 
  summarise(longest_books = max(num_pages)) %>% 
  arrange(desc(longest_books))

  #pull()

Longest_language_Code
```
Q6
```{r}
Highest_book_rating <- Good_reads %>% 
  select(language_code, average_rating) %>% 
  group_by(language_code) %>% 
  summarise(Highest_rating = max(average_rating)) #%>% 
  #pull()

Highest_book_rating
```

```{r}
Good_reads
```

```{r}
Earliest_releases <- Good_reads %>% 
  select(publisher, title, publication_date) %>% 
  group_by(publisher) %>% 
  arrange(publication_date) %>% 
  head(10)
  
Earliest_releases
```

```{r}
Latest_release <- Good_reads %>% 
  select(publisher, title, bookID, publication_date) %>% 
  group_by(publisher, publication_date) %>% 
  arrange(desc(publication_date)) %>% 
  head(10)

Latest_release
```

```{r}
Author_avg_rating <- Good_reads %>% 
  select(authors, average_rating, ratings_count) %>% 
  group_by(authors) %>% 
  mutate(avg_authors_rating = mean(average_rating)) %>% 
  arrange(desc(avg_authors_rating)) %>% 
  head(20)


Author_avg_rating
```

```{r}

longest_books <- Good_reads %>% 
  #slice_min(num_pages, n = 15) %>% 
  arrange(desc(num_pages)) %>% 
  head(15)



shortest_books <- Good_reads %>% 
  slice_max(num_pages, n = 10) %>% 
  arrange(num_pages) %>% 
  head(15)
```

```{r}
longest_books %>% 
  select(title, num_pages, publisher)

shortest_books
```

```{r}
isbn_organized <- Good_reads %>% 
  select(isbn, title, isbn13, bookID) %>% 
  distinct(isbn) %>% 
  arrange(desc(isbn)) %>% 
  head(15) #%>% 
  #pull()

isbn_organized

```

```{r}
spanish_authors <- Good_reads %>% 
  select(authors, language_code) %>% 
  group_by(language_code) %>% 
  filter(language_code == "spa")

spanish_authors
```

```{r}
range_of_languages <- Good_reads %>% 
  select(language_code, authors, title, bookID) %>% 
  group_by(language_code) #

range_of_languages
```

```{r}
how_many_pages <- Good_reads %>% 
  select(title, bookID, num_pages, authors) %>% 
  group_by(num_pages) %>% 
  arrange(desc(num_pages)) %>% 
  print(range(num_pages, na.rm = TRUE)) #%>% 
  

how_many_pages  
```

```{r}
Good_reads %>% 
  print(max(num_pages, na.rm=TRUE)-min(num_pages, na.rm=TRUE))
```

```{r}
range_of_pages <- Good_reads %>% 
  select(num_pages, title, bookID, authors) %>% 
  group_by(title) %>% 
  slice_max(num_pages, n = 1) %>%
  slice_min(num_pages, n = 1) %>% 
  print(slice_max(num_pages, n = 1) - slice_min(num_pages, n = 1))

range_of_pages
  
  
```

```{r}
Highest_page_count <- Good_reads %>% 
  select(language_code, num_pages) %>% 
  summarise(num_pages, language_code) %>% 
  arrange(desc(num_pages))


Highest_page_count
```

```{r}
range_of_pages <- Good_reads %>% 
  slice_max(num_pages)

range_of_pages

```

```{r}
Good_reads
books_readlength <- Good_reads %>%
  mutate(num_pages = na_if(num_pages, 0))

books_readlength %>% 
  summarise(count = sum(is.na(num_pages)))            
```

```{r}
books_imputed <- Good_reads %>%  
  mutate(num_pages = coalesce(num_pages, median(num_pages, na.rm = TRUE)))

books_imputed %>% 
  summarise(count = sum(is.na(num_pages)))
```

```{r}
short_books <- Good_reads %>% 
  mutate(num_pages = if_else(num_pages < 1000, median(num_pages), num_pages))
```

```{r}
books_reduced <- Good_reads %>% 
  select(-bookID, -isbn, -isbn13)

pub_highest_ratings <- books_reduced %>% 
  filter(ratings_count > 25) %>% 
  group_by(publisher) %>%
  summarize(mean_ratings = mean(average_rating, na.rm = TRUE)) %>% 
  arrange(desc(mean_ratings)) %>% 
  slice_head(n = 1)

pub_highest_ratings
```

```{r}
books_language <- Good_reads %>% 
  group_by(language_code) %>% 
  slice_max(num_pages, n = 1) %>% 
  select(language_code, title, num_pages)

books_language
```

