```{r}
library(prob)
library(tidyverse)
library(janitor)
library(fastGraph)
library(infer)
library(e1071)
```
Q1
```{r}
ames_data <- read_csv('data/ames.csv') %>% 
  clean_names() %>% 
  drop_na(lot_frontage)
```
Q2
```{r}
biggest_lots <- ames_data %>% 
  # group_by(lot_area) %>%
  # summarise(count = n()) %>%
  arrange(desc(lot_area)) %>%
  top_n(10)

biggest_lots
```
```{r}
ames_data %>% 
  summarise(range_lot = max(lot_area) - min(lot_area))
```


```{r}
ames_data %>% 
  ggplot() +
  aes(lot_area) +
  geom_histogram(fill = "green", binwidth = 750)
```

```{r}
ames_data %>% 
  
  group_by(order) %>%
  summarise(
    Q1 = quantile(lot_area, 0.25),
    Q2 = quantile(lot_area, 0.5),
    Q3 = quantile(lot_area, 0.75)
  )
```

```{r}
ames_stats <- ames_data %>% 
  summarise(num = n(),
            mean = mean(lot_area),
            sd = sd(lot_area))
ames_stats
ames_ratings <- ames_data %>%
  # filter(brand == "Samsung") %>%
  select(lot_area)

ames_ratings %>%
  ggplot(aes(x = lot_area)) +
  geom_histogram(aes(y = ..density..), col = "white") +
  stat_function(
    fun = dnorm, 
    args = list(
      mean = ames_stats$mean,
      sd = ames_stats$sd
    ),
    col = "red"
  )
```

```{r}
# ames_data
ames_summary <- . %>% 
  summarize(
    mean_lot_area = mean(lot_area),
    mean_frontage = mean(lot_frontage) 
    
  )
```
```{r}
ames_data %>% 
  ames_summary()
```

Q3
```{r}
mean_ames <- ames_data %>% 
  mutate(mean_lot = mean(lot_area))
mean_ames
bootstrap_ames <- mean_ames %>% 
  specify(response = lot_area) %>% 
  generate(reps = 5000, type = "bootstrap") %>% 
  calculate(stat = "mean")
  
infer_ames <- mean_ames %>% 
  get_ci(level = 0.95, type = "percentile")

bootstrap_ames %>% 
  visualize(bins = 40) + 
  shade_ci(endpoints = infer_ames)
  

```

```{r}
threshold <- 0.05
new_ames_95 <- mean_ames %>% 
  summarize(
    mean = mean(lot_area),
    lower_bound = quantile(mean_lot, probs = threshold),
    upper_bound = quantile(mean_lot, probs = 1 - threshold)
  )
new_ames_95 

infer_ames2 <- mean_ames %>% 
  get_ci(level = 0.95, type = "percentile")

mean_ames %>% 
  visualise(bins = 40) %>% 
  shade_ci(endpoints = infer_ames2)
```

```{r}
threshold <- 0.01
new_ames_95 <- mean_ames %>% 
  summarize(
    mean = mean(lot_area),
    lower_bound = quantile(mean_lot, probs = threshold),
    upper_bound = quantile(mean_lot, probs = 1 - threshold)
  )
new_ames_95 

infer_ames3 <- mean_ames %>% 
  get_ci(level = 0.99, type = "percentile")

mean_ames %>% 
  visualise(bins = 40) %>% 
  shade_ci(endpoints = infer_ames3)
```

Q6
```{r}
point_estimate_ames <- mean_ames %>% 
  mean(mean_lot, na.rm = TRUE)
```

