```{r}
library(styler)
```

```{r}
library(tidyverse)
```
```{r}
library(janitor)
```

```{r}
movies <- read_csv('6_homework_cleaning_data/data/movies.csv')

movies

```

```{r}
head(movies)

tail(movies)

nrow(movies)

ncol(movies)

dim(movies)

sum(is.na(movies))

nrow(movies) - nrow(drop_na(movies))
```

```{r}
movies %>% 
  filter(runtime < 10)
```

```{r}
movies_selected <- movies %>% 
  select(title, runtime, budget)

movies_selected

```

```{r}
filter(movies_selected, runtime == 0, budget == 0)

```
```{r}

```


```{r}
movies %>% 
  summarize(na_count = sum(is.na(movies_selected)))
```

```{r}
styler::style
movies %>%
  select(runtime) %>% 
  arrange(runtime) %>% 
  filter(runtime == 0) %>% 
  #filter(budget == 0) %>% 
  mutate(runtime_null = na_if(runtime, 0)) 

```

```{r}
movies %>% 
  mutate(runtime = na_if(runtime == 0))
```

```{r}
movies_inputed <- movies %>% 
  mutate(runtime = coalesce(runtime == 0, 'unavailable'))
```

```{r}
movies %>%
  mutate(runtime = coalesce(runtime))
```

```{r}
summary(movies, runtime < 10)
```

```{r}
movies %>% 
mutate(movies_runtime = na_if(runtime == 0))
```

```{r}
movies %>% 
  slice_max(runtime, n = 5, with_ties = FALSE)
```

```{r}
movies_selected %>% 
  replace_with_na(replace(runtime == 0))
```

```{r}
movies_runtime <- movies_selected %>% 
  mutate(runtime = na_if(runtime, 0))

movies_runtime

movies_runtime %>% 
  count(is.na(runtime))
```

```{r}
movies_selected %>% 
  summarise(na_runtime = sum(is.na(runtime)),
            na_title = sum(is.na(title)),
            na_budget = sum(is.na(budget)))
```
Question_4
```{r}
movies_runtime <- movies_selected %>%
  mutate(runtime = na_if(runtime, 0))

movies_runtime %>% 
  summarise(count = sum(is.na(runtime)))
```
Question_5
```{r}
movies_imputed <- movies_runtime %>%  
  mutate(runtime = coalesce(runtime, median(runtime, na.rm = TRUE)))

movies_imputed %>% 
  summarise(count = sum(is.na(runtime)))
```
Question_6
```{r}
movies_imputed %>% 
  slice_min(runtime, n = 10)

movies_imputed %>% 
  slice_max(runtime, n = 10)
```
Question_7
```{r}
movies_imputed <- movies_imputed %>% 
  mutate(budget = if_else(budget < 100, median(budget), budget))
```
Extension_Q1
```{r}
movie_budgets <- movies_imputed %>%
  mutate(
    budget_type = case_when(
      budget < 12e6 ~ "Small budget",
      budget < 40e6 ~ "Medium budget",
      budget >= 40e6 ~ "Big budget"
      )
    )

movie_budgets
```
Extension_Q2
```{r}
movies %>%
  summarise(across(where(is.numeric), ~sum(is.na(.x))))

movies %>%
  summarise(across(where(is.character), ~sum(is.na(.x))))
```

```{r}
movies_runtime <- movies_selected %>% 
  mutate(runtime = na_if(runtime, 0))

runtime_median <- median(movies_runtime$runtime, na.rm = TRUE)

movies_imputed <- movies_runtime %>% 
      mutate(runtime = coalesce(runtime, runtime_median)) %>% 
      arrange(runtime)

movies_imputed %>% 
  count(is.na(runtime))
```

```{r}
movies %>%
  summarise(across(where(is.numeric), ~sum(is.na(.x))))

movies %>%
  summarise(across(where(is.character), ~sum(is.na(.x))))
```

```{r}
movies_imputed %>% 
  view()
```

```{r}
movies_selected %>% 
  mutate(runtime = na_if(runtime, 0), 
         runtime = coalesce(runtime, median(runtime, na.rm = TRUE))) %>% 
  summarise(sum(is.na(runtime)))
```

```{r}
movies_imputed %>% 
  mutate(budget = ifelse(budget < 100, median(budget), NA))

```

```{r}
movie_budgets <- movies_imputed %>% 
  mutate(budget_type = case_when(
                                budget <= 12e6 ~ "Small Budget",
                                budget < 40e6 & budget > 12e6 ~ "Medium Budget",
                                budget >= 40e6 ~ NA_character_
                                )
        )
```

```{r}
movies %>% 
  summarise(across(where(is.numeric),
                   ~sum(is.na(.x)),
                   .names = "missing_values_in_{col}")) #%>%
  #summarise(across(everything(), sum, .names = "missing_values_in_{col}"))


movies %>% 
  summarise(across(
                  where(is.numeric),
                   is.na
                  )
            ) %>%
  summarise(across(everything(), sum, .names = "missing_values_in_{col}"))
```

```{r}
movies %>% 
  summarise(across(where(is.numeric),
                   ~sum(is.na(.x)),
                   .names = "missing_values_in_{col}"))

movies %>% 
  summarise(across(
    where(is.numeric),
    is.na)
    )
  ) %>%
  summarise(across(everything(), sum, .names = 
"missing_values_in_{col}"))
```

```{r}
summary(movies)
```

```{r}
class(summary(movies))
```

