```{r}
library(tidyverse)
library(CodeClanData)
library(janitor)
library(assertr)
library(readr)
```
Q1
```{r}
backpack
dim(backpack)
names(backpack)
head(backpack)
tail(backpack)
sum(is.na(backpack))
```
Q2
```{r}
backpack %>% 
  ggplot(aes(x = year, y = backpack_weight, colour = major)) +
  geom_point()
```
Q3
```{r}
Backpack_weights <- backpack %>% 
  group_by(sex) %>% 
  summarise(mean_weight = mean(backpack_weight))

ggplot(Backpack_weights, aes(x = sex, y = mean_weight)) +
  geom_col()
```

Q4: Correlation between body weight and backpack weight
```{r}
backpack %>% 
  ggplot(aes(x = year, y = backpack_weight, fill = body_weight)) +
  geom_col() +
  labs(x = "Year", y = "Backpack weight")
```
Q5: Correlation of body weight and backpack weight between genders
```{r}
backpack_F <- backpack %>% 
  filter(sex == "Female")

backpack_M <- backpack %>% 
  filter(sex == "Male")
 
  ggplot(backpack_F, aes(x = year, y = backpack_weight, fill = body_weight)) +
  geom_col() +
  labs(x = "Year", y = "Backpack weight")
  
  ggplot(backpack_M, aes(x = year, y = backpack_weight, fill = body_weight)) +
  geom_col() +
  labs(x = "Year", y = "Backpack weight")
```
Q6: Pie chart for proportion
```{r}
backpack %>% 
  ggplot(aes(x = back_problems, y = major, fill = ratio)) +
  geom_col()
  coord_polar("y", start=0)

```

