```{r}
library(tidyverse)
library(CodeClanData)
library(janitor)
```
q1
```{r}
Weather_forecast_triduum <- list(
  Thursday = list(rain_chance = "high", wind_mph = 35, temperature_C = 13),
  Friday = list(rain_chance = "low", wind_mph = 25, temperature_C = 16),
  Saturday = list(rain_chance = "low", wind_mph = 19, temperature_C = 22)
)
Weather_forecast_triduum
```
q2
```{r}
Weather_forecast_triduum$Thursday$rain_chance
```

```{r}
Weather_forecast_triduum$Friday$wind_mph
```

```{r}
Weather_forecast_triduum$Thursday$temperature_C
```

q3
```{r}
weather_matrix <- matrix(1:7, nrow = 2, ncol = 7)
#weather_matrix
# for (row_num in 1:dim(weather_matrix)[1]){
#   for (col_num in 1:dim(weather_matrix)[2]){
#     weather_matrix[row_num, col_num] <-  row_num * col_num
#   }
# }
weather_matrix
```

q4
```{r}
weather_matrix[2,3]
weather_matrix[2]
weather_matrix[1,1]
weather_matrix[1,5]
weather_matrix[2,5]
weather_matrix[1,3]
```

```{r}
#rownames(x) <- list(c)
# weather_matrix
# for (row_num in 1:dim(weather_matrix)[1]){
#   for (col_num in 1:dim(weather_matrix)[2]){
#     product_matrix[row_num, col_num] <-  row_num * col_num
#   }
# }
# product_matrix
```
q5
```{r}
The_answer_is <- function(x) {
  if(x < 10){
    return(x)
      if(x == 10 * 0) OR
      if(x == 10 %% 0)
        print("The answer is", x) 
    } else {
      print("Invalid Input")
    }
    }
  
  
          
          
        
```

```{r}
a <- c(1, 2, 3)
b <- c(1, 3, 2)

a == b

sort(a) == sort(b)

all(a == b)

Similarity_checker <- function(x){
  if (a == b) {
    print("Exactly the same")
    print("The same")
    print("Different")
  }
}
```

q6
```{r}
a <- c(1, 2, 3)
b <- c(1, 3, 2)

a == b

sort(a) == sort(b)

all(a == b)
if (all(a %in% b{
  DO SOMETHING IF TRUE
}else{
 if(all( ADD ANOTHER COMPISON USING SORT)){
    DO SOMETHING ELSE HERE
  }else{
    DO YOUR FINAL THING HERE
  }
}
#  vector_1 <- c(1, 2, 3, 4, 8)
# vector_2 <- c(2, 4, 8, 6, 10)
# Similarity_checker <- function(x){
#   if(vector_1 ==){
#     
#   } else {
#     print("Different")
#   }
# }
```

```{r}
# from learn-r.org
number <- as.integer(readline(prompt = "Please enter a number for a table"))
for( t in 1:12)

{

    print ( paste (number, '*', t, '=', number * t))

}
```

