---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
library(CodeClanData)
```

```{r}
CodeClanData::drinks_content
```

```{r}
library(CodeClanData)
drinks_content
```

```{r}
nrow(drinks_content)
```

```{r}
ncol(drinks_content)
```
```{r}
str(drinks_content)
```

```{r}
select(drinks_content, Beverage_category, Beverage, Beverage_prep, Calories)
```

```{r}
filter(drinks_content, Beverage_category)

```

```{r}
drop_na(drinks_content, Calories)
```

```{r}
sum(drinks_content$ Calories - 135)
```

```{r}
arrange(drinks_content, Calories)
```

```{r}
sum(drinks_content, Calories - 135)
```

```{r}
calorie_diff <- c(drinks_content, Calories - 135)

calorie_diff(Beverage_category)
```
```{r}
summarise(drinks_content(mean(Calories)))
```

```{r}
calorie_diff <- c(drinks_content, Calories - 135)
```
```{r}
arrange(drinks_content, Calories)
```
```{r}
drinks_content
```

```{r}
mutate(drinks_content,
       Calories = as.numeric(Calories))

```
```{r}
Calorie_count <- select(drinks_content, Calories)

calorie_diff <- sum(Calorie_count - 135)

calorie_diff(drinks_content, Beverage_category)
```


```{r}
summarise(drinks_content, calorie_diff = sum(Calories %in% Beverage_category - 135))
```

```{r}
calorie_diff <- summarise(drinks_content, sum(Calories - 135))


```

```{r}
# first 5 rows
head(drinks_content,5)

# last 5 rows
tail(drinks_content,5)

# get the dimensions
dim(drinks_content)

# get variable names 
names(drinks_content)

```
```{r}
drinks_content %>%
  select(Beverage_category, Beverage, Beverage_prep, Calories) %>%
  filter(is.na(Calories)) %>%
  summarise(count_of_missing_calories = n())
```
```{r}
drink_calories <- drinks_content %>%
  mutate(calorie_diff = Calories - 135)

```

```{r}
most_calories <- drink_calories %>%
  group_by(Beverage_category) %>%
  summarise(mean_calories = mean(Calories)) %>%
  arrange(desc(mean_calories)) %>%
  head(3)

most_calories
```

```{r}
least_calories <- drink_calories %>%
  group_by(Beverage_category) %>%
  summarise(mean_calories = mean(Calories)) %>%
  arrange(mean_calories)%>%
  head(3)

least_calories
```

```{r}
# work out the mean calories for each beverage prep 
average_bev_prep <- drink_calories %>%
  group_by(Beverage_prep) %>%
  summarise(mean_cals = mean(Calories)) %>%
  arrange(desc(mean_cals))

average_bev_prep
```

```{r}
# find the average calories - and we need to use pull() to be able to use the number in calculations
avg_calories <- drink_calories %>%
                  summarise(mean_calories = mean(Calories)) %>%
                  pull()

avg_calories 
```

```{r}
# find which prep types have above average calories
above_avg_calories <- average_bev_prep %>%
  filter(mean_cals >= avg_calories)

above_avg_calories
```

```{r}
# we also could have done it using mutate and then filter 

average_bev_prep %>%
  mutate(is_greater_than_avg = mean_cals >= avg_calories) %>%
  filter(is_greater_than_avg == TRUE)
```

```{r}
head(drink_calories)

# can start by finding the drink with the lowest number of calories 
drink_calories %>%
  group_by(Beverage_category, Beverage, Beverage_prep) %>%
  summarise(min_calories = min(Calories)) %>%
  arrange(min_calories) %>%
  head(1)

# But this is a Tea and the answer specifically asked for coffee drink! So we will filter out this tea drink to get the lowest calorie coffee drink.


drink_calories %>%
  filter(Beverage_category != "Tazo® Tea Drinks") %>%
  group_by(Beverage_category, Beverage, Beverage_prep) %>%
  summarise(min_calories = min(Calories)) %>%
  arrange(min_calories) %>%
  head(1)
```

```{r}
df <- tibble(x = 1, y = 2)

mutate(df, z = x + y, .after = x)
```


